services:
  localstack:
    build:
      context: .
      dockerfile: Dockerfile.localstack
    container_name: "localstack"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
    volumes:
      - localstack_data:/data/localstack  # Volumen nombrado dentro del contenedor
      - /create_resources.sh:/create_resources.sh
    networks:
      - mora-database-network
      
  db:
    image: mongo
    restart: always
    hostname: 'undidb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mgdbkoral2023*
      DATABASE_URI: "mongodb://root:mgdbkoral2023*@localhost:27017/undidb?authSource=admin&readPreference=primary&ssl=false&directConnection=true"
    volumes:
      - mongodata:/data/db
      - ../ma-coreapi/database/:/ma-coreapi_seed_scripts/
      - ../ma-calculations/database/:/ma-calculations_seed_scripts/
    ports:
      - "27017:27017"
    networks:
      - mora-database-network

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"

  web-sockets:
    image: web-sockets-server:latest
    build: ../mora-web-sockets/
    restart: no
    hostname: 'web-sockets'
    ports: 
        - 6001:6001
    expose:
      - 6001
    command: npm run start


volumes:
  mongodata:
  localstack_data:  # Volumen nombrado para los datos de LocalStack

networks:
  mora-database-network:
    driver: bridge
